version: '3.9'

services:

  dms:
    image: andrglo/everest:latest
    hostname: mssql-cr-layer
    container_name: mssql-cr-layer-dms-1
    command: tail -f /dev/null
    working_dir: /root/mssql-cr-layer
    volumes:
      - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/root/mssql-cr-layer
    environment:
      - NODE_ENV=test
      - MSSQL_PASSWORD=Juriti01
      - MSSQL_HOST=mssql
    restart: always

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-20.04
    container_name: mssql-cr-layer-mssql-1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Juriti01
      - MSSQL_PID=Express
      - MSSQL_COLLATION=Latin1_General_CI_AI
    restart: always


